### ISSUE TITLE
eval the toolkit calculates the recall incorrectly

### ISSUE THREAD

**Issue by wxyucs** [antgroup/vsag#408]
**Describe the bug**
run with dataset `sift-1m` got recall 0%
```
{
    "action": "search",
    "dataset_info": {
        "base_count": 1000000,
        "data_type": "float32",
        "dim": 128,
        "filepath": "/data/sift-128-euclidean.hdf5",
        "query_count": 10000
    },
    "index_info": {
        "dim": 128,
        "dtype": "float32",
        "hnsw": {
            "base_quantization_type": "fp32",
            "ef_construction": 400,
            "max_degree": 16
        },
        "metric_type": "l2"
    },
    "latency_avg(ms)": 1.685406760300003,
    "latency_detail(ms)": {
        "p50": 1.744323,
        "p80": 1.910656,
        "p90": 1.979191,
        "p95": 2.02833,
        "p99": 2.115812
    },
    "memory_peak(KB)": 1311900,
    "qps": 593.3285801120198,
    "recall_avg": 0.0,
    "recall_detail": {
        "p0": 0.0,
        "p10": 0.0,
        "p30": 0.0,
        "p50": 0.0,
        "p70": 0.0,
        "p90": 0.0
    },
    "search_mode": "knn",
    "search_param": "{\"hnsw\":{\"ef_search\":400}}"
}
```

**To Reproduce**
eval_template.yaml:
```yaml
eval_case1:
    datapath: "/data/sift-128-euclidean.hdf5"
    type: "search" # build, search
    index_name: "hnsw"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","hnsw":{"base_quantization_type":"fp32","max_degree":16,"ef_construction":400}}'
    search_params: '{"hnsw":{"ef_search":400}}'
    index_path: "/tmp/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5
```
