### ISSUE TITLE
segmentation fault occupied when search on a deserialized hgraph index

### ISSUE THREAD

**Issue by wxyucs** [antgroup/vsag#416]
**Describe the bug**
crash on searching a persistent hgraph index

**To Reproduce**
```yaml
# tools/eval/eval_template.yaml

eval_case1:
    datapath: "/data/sift-128-euclidean.hdf5"
    type: "search" # build, search
    index_name: "hgraph"
    create_params: '{"dim":128,"dtype":"float32","metric_type":"l2","index_param":{"base_quantization_type":"fp32","max_degree":32,"ef_construction":400}}'
    search_params: '{"hgraph":{"ef_search":60}}'
    index_path: "/data/sift-128-euclidean/index/hgraph_index"
    topk: 10
    search_mode: "knn" # ["knn", "range", "knn_filter", "range_filter"]
    range: 0.5

```

**Environment**
- vsag version: 0877ef1700813deeffc9dd3bab7e9ddb8b738bf3

**Screenshots**

![Image](https://github.com/user-attachments/assets/556e535d-3b88-47cb-8523-f2e468ee4b6a)
